//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyBota.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArizaBildirimItem
    {
        public int Id { get; set; }
        public int ArizaBildirimHeaderId { get; set; }
        public int AcilanArizaTanimId { get; set; }
        public int KapananArizaTanimId { get; set; }
        public int TechizatTuruId { get; set; }
        public int PotaKartId { get; set; }
        public int BilesenHeaderId { get; set; }
        public int BilesenItemId { get; set; }
    }
}
