//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyBota.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArizaTanim
    {
        public int Id { get; set; }
        public int ArizaTechizatGrubuId { get; set; }
        public string ArizaTanimAdi { get; set; }
        public int ArizaTanimGrupId { get; set; }
        public int OnemDerecesi { get; set; }
    }
}
