//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyBota.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PotaKart
    {
        public int Id { get; set; }
        public string PotaKartAdi { get; set; }
        public int TechizatTuruId { get; set; }
        public string PotaKodu { get; set; }
        public int BolumId { get; set; }
        public int KomponentTanimId { get; set; }
        public int KomponentTanimGrupId { get; set; }
        public bool SeciliMi { get; set; }
        public int SilinsinMi { get; set; }
    }
}
