//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyBota.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewArizaGuncelDurum
    {
        public int DepartmanId { get; set; }
        public int UserId { get; set; }
        public int ArizaDurumu { get; set; }
        public string ArizaDurumuAdi { get; set; }
        public string Name { get; set; }
        public int ArizaMudahaleYetki { get; set; }
        public int ArizaBildirimYetki { get; set; }
    }
}
