//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyBota.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZamanEtuduItemDeger
    {
        public int Id { get; set; }
        public int ZamanEtuduItemId { get; set; }
        public int Sira { get; set; }
        public int ItemDegeri { get; set; }
        public int UserId { get; set; }
    }
}
